<a href="https://colab.research.google.com/github/aradeyal/machine_learning/blob/main/PandasQ1a_for_students.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(1)
np1= np.random.randint(0,100,30).reshape(5,6)
np1

array([[37, 12, 72,  9, 75,  5],
       [79, 64, 16,  1, 76, 71],
       [ 6, 25, 50, 20, 18, 84],
       [11, 28, 29, 14, 50, 68],
       [87, 87, 94, 96, 86, 13]])

In [ ]:
df = pd.DataFrame(np1)
df.columns=['A','B','C','D','E','F']
df.index=['a','b','c','d','e']
df

    A   B   C   D   E   F
a  37  12  72   9  75   5
b  79  64  16   1  76  71
c   6  25  50  20  18  84
d  11  28  29  14  50  68
e  87  87  94  96  86  13

In [ ]:
#FINISHED

a    12
b    64
c    25
d    28
e    87
Name: B, dtype: int64

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1)
np1 = np.random.randint(0, 100, 30).reshape(5, 6)

df = pd.DataFrame(np1)
df.columns = ['A', 'B', 'C', 'D', 'E', 'F']
df.index = ['a', 'b', 'c', 'd', 'e']

print(df["B"])

a    12
b    64
c    25
d    28
e    87
Name: B, dtype: int64

In [ ]:
#FINISHED

A     6
B    25
C    50
D    20
E    18
F    84
Name: c, dtype: int64

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1)
np1 = np.random.randint(0, 100, 30).reshape(5, 6)

df = pd.DataFrame(np1)
df.columns = ['A', 'B', 'C', 'D', 'E', 'F']
df.index = ['a', 'b', 'c', 'd', 'e']

print(df.loc["c"])

A     6
B    25
C    50
D    20
E    18
F    84
Name: c, dtype: int64

In [ ]:
#FINISHED

20

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1)
np1 = np.random.randint(0, 100, 30).reshape(5, 6)

df = pd.DataFrame(np1)
df.columns = ['A', 'B', 'C', 'D', 'E', 'F']
df.index = ['a', 'b', 'c', 'd', 'e']

print(df.loc["c", "D"])

20

In [ ]:
df.loc[['c','e'],['B','F']]
#using df.loc

    B   F
c  25  84
e  87  13

In [ ]:
#FINISHED

    C   D
c  50  20
d  29  14
e  94  96

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1)
np1 = np.random.randint(0, 100, 30).reshape(5, 6)

df = pd.DataFrame(np1)
df.columns = ['A', 'B', 'C', 'D', 'E', 'F']
df.index = ['a', 'b', 'c', 'd', 'e']

df.loc[["c", "d", "e"], ["C", "D"]]

    C   D
c  50  20
d  29  14
e  94  96

In [ ]:
#FINISHED

    A   C   D   E   F
a  37  72   9  75   5
b  79  16   1  76  71
c   6  50  20  18  84
d  11  29  14  50  68
e  87  94  96  86  13

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1)
np1 = np.random.randint(0, 100, 30).reshape(5, 6)

df = pd.DataFrame(np1)
df.columns = ['A', 'B', 'C', 'D', 'E', 'F']
df.index = ['a', 'b', 'c', 'd', 'e']

df.loc[["a", "b", "c","d","e"], ["A","C" ,"D","E","F"]]

    A   C   D   E   F
a  37  72   9  75   5
b  79  16   1  76  71
c   6  50  20  18  84
d  11  29  14  50  68
e  87  94  96  86  13

In [ ]:
#FINISHED

    A   B   C   D   E   F
b  79  64  16   1  76  71
c   6  25  50  20  18  84
d  11  28  29  14  50  68

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1)
np1 = np.random.randint(0, 100, 30).reshape(5, 6)

df = pd.DataFrame(np1)
df.columns = ['A', 'B', 'C', 'D', 'E', 'F']
df.index = ['a', 'b', 'c', 'd', 'e']

df.loc[["b", "c","d"], ["A","B","C" ,"D","E","F"]]

    A   B   C   D   E   F
b  79  64  16   1  76  71
c   6  25  50  20  18  84
d  11  28  29  14  50  68

In [ ]:
#FINISHED

    A   B   C   D   E   F    G
a  37  12  72   9  75   5   80
b  79  64  16   1  76  71  147
c   6  25  50  20  18  84  102
d  11  28  29  14  50  68  118
e  87  87  94  96  86  13   99

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(1)
np1 = np.random.randint(0, 100, 30).reshape(5, 6)

df = pd.DataFrame(np1)
df.columns = ['A', 'B', 'C', 'D', 'E', 'F']
df.index = ['a', 'b', 'c', 'd', 'e']
df["G"] = df["E"] + df["F"]

df

    A   B   C   D   E   F    G
a  37  12  72   9  75   5   80
b  79  64  16   1  76  71  147
c   6  25  50  20  18  84  102
d  11  28  29  14  50  68  118
e  87  87  94  96  86  13   99

In [ ]:
#fill in to get the below result

a     True
b    False
c     True
d    False
e     True
Name: C, dtype: bool

In [ ]:
df["C"] > 30

a     True
b    False
c     True
d    False
e     True
Name: C, dtype: bool

In [ ]:
[df['C'] > 30]

[a     True
 b    False
 c     True
 d    False
 e     True
 Name: C, dtype: bool]

In [ ]:
(df['B'] > 20) & (df['D']<80)
 # column B greater than 20 and column D less than 80

a    False
b     True
c     True
d     True
e    False
dtype: bool

In [ ]:
df[(df['B'] > 20) & (df['D']<80)]
#הצגת שורות של התנאי הקודם

    A   B   C   D   E   F    G
b  79  64  16   1  76  71  147
c   6  25  50  20  18  84  102
d  11  28  29  14  50  68  118

In [ ]:
df > 50
# all items bigger than 50

       A      B      C      D      E      F     G
a  False  False   True  False   True  False  True
b   True   True  False  False   True   True  True
c  False  False  False  False  False   True  True
d  False  False  False  False  False   True  True
e   True   True   True   True   True  False  True

In [ ]:
df[df>50]
# הצגת כל התאים שמקיימים תנאי קודם

      A     B     C     D     E     F    G
a   NaN   NaN  72.0   NaN  75.0   NaN   80
b  79.0  64.0   NaN   NaN  76.0  71.0  147
c   NaN   NaN   NaN   NaN   NaN  84.0  102
d   NaN   NaN   NaN   NaN   NaN  68.0  118
e  87.0  87.0  94.0  96.0  86.0   NaN   99